# Generated by Django 3.2.4 on 2021-06-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
    ]
