# Generated by Django 3.2.4 on 2021-06-26 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210626_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='image',
            name='original_filename',
            field=models.CharField(default='noimage', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(default='np_public-id', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='secure_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
